name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install libssl1.1 for mongodb-memory-server
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1 || \
            (wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl1.1/libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb && \
            sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.22_amd64.deb)

      - name: Install dependencies (use npm ci when lockfile exists)
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ] || [ -f yarn.lock ]; then
            echo "Lockfile found — running npm ci"
            npm ci
          else
            echo "No lockfile found — running npm install"
            npm install
          fi

      - name: Run tests
        run: npm test